game.resources = [
    // images
    {name: "clumsy1", type:"image", src: "data/img/clumsy1.png"},
    {name: "clumsy2", type:"image", src: "data/img/clumsy2.png"},
    {name: "clumsy3", type:"image", src: "data/img/clumsy3.png"},
    {name: "databasebg", type:"image", src: "data/img/databasebg.png"},
    {name: "benchmarkbg", type:"image", src: "data/img/benchmarkbg.png"},
    {name: "mysqlbutton", type:"image", src: "data/img/mysqlbutton.png"},
    {name: "oraclebutton", type:"image", src: "data/img/oraclebutton.png"},
    {name: "tpccbutton", type:"image", src: "data/img/tpccbutton.png"},
    {name: "ycsbbutton", type:"image", src: "data/img/ycsbbutton.png"},
    {name: "newbutton", type:"image", src: "data/img/newbutton.png"},
    {name: "retrybutton", type:"image", src: "data/img/retrybutton.png"},
    {name: "pipe1", type:"image", src: "data/img/pipe1.png"},
    {name: "pipe2", type:"image", src: "data/img/pipe2.png"},
    {name: "pipe3", type:"image", src: "data/img/pipe3.png"},
    {name: "bg1", type:"image", src: "data/img/bg1.png"},
    {name: "bg2", type:"image", src: "data/img/bg2.png"},
    {name: "bg3", type:"image", src: "data/img/bg3.png"},
    {name: "ground1", type:"image", src: "data/img/ground1.png"},
    {name: "ground2", type:"image", src: "data/img/ground2.png"},
    {name: "ground3", type:"image", src: "data/img/ground3.png"},
    {name: "ground", type:"image", src: "data/img/ground.png"},
    {name: "bg", type:"image", src: "data/img/bg.png"},
    {name: "logo", type:"image", src: "data/img/logo.png"},
    {name: "gameover", type:"image", src: "data/img/gameover.png"},
    {name: "gameoverbg", type:"image", src: "data/img/gameoverbg.png"},
    {name: "hit", type:"image", src: "data/img/hit.png"},
    {name: "getready", type:"image", src: "data/img/getready.png"},
    {name: "new", type:"image", src: "data/img/new.png"},
    {name: "share", type:"image", src: "data/img/share.png"},
    {name: "tweet", type:"image", src: "data/img/tweet.png"},
    // sounds
    {name: "theme", type: "audio", src: "data/bgm/"},
    {name: "hit", type: "audio", src: "data/sfx/"},
    {name: "lose", type: "audio", src: "data/sfx/"},
    {name: "wing", type: "audio", src: "data/sfx/"},
];
