game.resources = [
    // images
    {name: "clumsy1", type:"image", src: "data/img/clumsy.png"},
    {name: "clumsy2", type:"image", src: "data/img/fruit.png"},
    {name: "clumsy3", type:"image", src: "data/img/clumsy1.png"},
    {name: "clumsy", type:"image", src: "data/img/clumsy.png"},
    {name: "databasebg", type:"image", src: "data/img/databasebg.png"},
    {name: "benchmarkbg", type:"image", src: "data/img/benchmarkbg.png"},
    {name: "mysqlbutton", type:"image", src: "data/img/mysqlbutton.png"},
    {name: "timestenbutton", type:"image", src: "data/img/timestenbutton.png"},
    {name: "postgresbutton", type:"image", src: "data/img/postgresbutton.png"},
    {name: "nuodbbutton", type:"image", src: "data/img/nuodbbutton.png"},
    {name: "tpccbutton", type:"image", src: "data/img/tpccbutton.png"},
    {name: "ycsbbutton", type:"image", src: "data/img/ycsbbutton.png"},
    {name: "newbutton", type:"image", src: "data/img/newbutton.png"},
    {name: "retrybutton", type:"image", src: "data/img/retrybutton.png"},
    {name: "pipe", type:"image", src: "data/img/pipe.png"},
    {name: "pipe1", type:"image", src: "data/img/goldpipe.png"},
    {name: "pipe2", type:"image", src: "data/img/icepipe.png"},
    {name: "pipe3", type:"image", src: "data/img/pipe.png"},
    {name: "bg", type:"image", src: "data/img/bg.png"},
    {name: "bg1", type:"image", src: "data/img/ocean_background.png"},
    {name: "bg2", type:"image", src: "data/img/snowbg.png"},
    {name: "bg3", type:"image", src: "data/img/desertbg.png"},
    {name: "ground", type:"image", src: "data/img/ground.png"},
    {name: "ground1", type:"image", src: "data/img/seafloor.png"},
    {name: "ground2", type:"image", src: "data/img/icefloor.png"},
    {name: "ground3", type:"image", src: "data/img/desertfloor.png"},
    {name: "logo", type:"image", src: "data/img/logo.png"},
    {name: "plainframe", type:"image", src: "data/img/plainframe.png"},
    {name: "gameover", type:"image", src: "data/img/gameover.png"},
    {name: "gameoverbg", type:"image", src: "data/img/gameoverbg.png"},
    {name: "hit", type:"image", src: "data/img/hit.png"},
    {name: "getready", type:"image", src: "data/img/getready.png"},
    {name: "new", type:"image", src: "data/img/new.png"},
    {name: "share", type:"image", src: "data/img/share.png"},
    {name: "tweet", type:"image", src: "data/img/tweet.png"},
    // sounds
    {name: "theme", type: "audio", src: "data/bgm/"},
    {name: "hit", type: "audio", src: "data/sfx/"},
    {name: "lose", type: "audio", src: "data/sfx/"},
    {name: "wing", type: "audio", src: "data/sfx/"},
];
